# Generated by Django 5.1.2 on 2024-10-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_github',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
