# Generated by Django 5.1.2 on 2024-10-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_link_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag_tech',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
